# -*- coding: utf-8 -*-
"""Assignment12_CS_201951157.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GiX_UOH18CIt4VLhiTR7iEnc7Cfxhmyu

#CS312 DATA ANALYTICS AND VISUALIZATION  
#SUNIL BHENSPALIYA
#201951157 (CSE)
#LAB ASSIGNMENT :- 12
"""

import pandas as pd
import random
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

df_1 = pd.read_csv('/content/sample_data/cookie_cats (1).csv')
df_1.head()

result = stats.ttest_ind(df_1[df_1.version == 'gate_30'].sum_gamerounds,df_1[df_1.version == 'gate_40'].sum_gamerounds,equal_var=False)
print(f'The value of t will be : {result.statistic:.4f}')
print(f'The value for p for single sided test : {result.pvalue / 2:.4f}')

"""# Observation & Conclusion
- As we can observe that p-value is very higher than than the alpha (i.e. 0.05), so We should not reject the null hypothesis 
"""