# -*- coding: utf-8 -*-
"""Assignment3_CS_201951157.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HgGgwMobKU6sdzzB1ywCkc85FdVcIRDn

Assignment3_CS_201951157
Sunil bhenspaliya

Q.(1) Present the data from dataset using three appropriate plots explained in Class.
"""

pip install joypy

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.graphics.gofplots import qqplot
from joypy import joyplot

filepath="/content/sample_data/grains_production_india_from_2001_to_2017.csv"
dataset=pd.read_csv(filepath)
dataset

#data of all grains
data_grains = dataset.pivot_table(index="Year")
print(data_grains)

ax = sns.pointplot(data=data_grains, dodge=True, join=False)
ax.set_xticklabels(ax.get_xticklabels(),rotation = 90)

ax=sns.stripplot(data=data_grains)
ax=sns.violinplot(data=data_grains,color="0.4")
ax.set_xticklabels(ax.get_xticklabels(),rotation = 90)

joyplot(data_grains,overlap = 0)
plt.show()

# now taking only the data of FOOD GRAINS (CEREALS)
#removing the unwanted columns (all except cereals)
Cereals_data = dataset.drop(dataset.iloc[:,9:], inplace=False, axis=1)
Cereals_data

ax = sns.pointplot(data=Cereals_data, dodge=True, join=False)
ax.set_xticklabels(ax.get_xticklabels(),rotation = 90)

ax = sns.stripplot(data=Cereals_data)
ax = sns.violinplot(data=Cereals_data,color="0.4")
ax.set_xticklabels(ax.get_xticklabels(),rotation = 90)

joyplot(Cereals_data,overlap = 0)
plt.show()