# -*- coding: utf-8 -*-
"""Assignment10_CS_201951157.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HEUzj_88sCVb_dw9XTQDtxk-9yVLcdAe

#  Data Analytics And Visulation | 
```
-> SUNIL BHENSPALIYA
->LAB ASSIGNMENT -10
```
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns
import math
import matplotlib.pyplot as plt
import numpy as np
from google.colab import drive
sns.set(rc={'figure.figsize':(12,8)})

filepath="/content/drive/MyDrive/201951157/DA/loan-train.csv"
data = pd.read_csv(filepath)
data.head()

"""###1. Plot the histogram of the Applicant’s Income.

"""

data['ApplicantIncome'].hist()
plt.show()

sns.histplot(data['ApplicantIncome'])
plt.show()

column = data['ApplicantIncome']

Mean = (column - np.mean(column))/np.std(column)

print(f"Mean: {np.mean(Mean)}")
print(f"Standard deviation: {np.std(Mean)}")

sns.histplot(Mean, kde=True)
plt.show()

"""###2. Check the distribution of Applicant’s Income is a Normal Distribution or not using QQ plot."""

import pylab as py
import statsmodels.api as sm

sm.qqplot(Mean, line ='45')
py.show()