# -*- coding: utf-8 -*-
"""Assignment14_CS_201951157.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tf2k3JESp1VjygpGhkoVBaht9Lu8LuY2

#CS312 DATA ANALYTICS AND VISUALIZATION  
#SUNIL BHENSPALIYA
#201951157 (CSE)
#LAB ASSIGNMENT :- 14
"""

import numpy as np
import pandas as pd

data = pd.read_csv('/content/sample_data/IPL_Auction_2022_FullList.csv')
data.head()

table=pd.crosstab(data["Specialism"],data["Batting"],margins=True)
table

table=pd.crosstab(data["Specialism"],data["Batting"],margins=False)
table

import seaborn as sns
from scipy import stats

df=3
chi_data = stats.chi2.rvs(table)
sns.histplot(chi_data,kde=True)

from scipy import stats

chisq, pvalue, df, expected = stats.chi2_contingency(table)
print(f'Observed chi2: {chisq:.4f}')
print(f'p-value: {pvalue:.4f}')